### PR TITLE
Update with material from TF-A 7th May Tech Forum

### PR DESCRIPTION
**Pull request by joannafarley-arm**

### CODE REVIEW

**Comment by joannafarley-arm** [comment]
Nay chances of getting this merged?

**Comment by sandrine-bailleux-arm** [comment]
Hi @joannafarley-arm ,

The first patch ("TF-A TechForum from 7th May session update") in the series looks good to me. Regarding the patches adding the CMake slides, could we squash the 3 patches into a single one that introduces the right file from the beginning? Right now, it seems to me that you've added a first version then removed it and finally uploaded the right one. Or did I misunderstand?

**Comment by joannafarley-arm** [comment]
Hi Sandrine, sort of. It was the right file but had spaces in its name which I had not noticed and when I did I predicted that the link test was likely to fail so replaced it. How do I squash via the git hub interface without starting again?

**Comment by sandrine-bailleux-arm** [comment]
> How do I squash via the git hub interface without starting again?

You should be able to squash the 3 patches (using an interactive git rebase) then push the patches again to Github and I expect that this should just update your existing pull request.

**Comment by joannafarley-arm** [comment]
So you cannot when working in GitHub only it seems like I have been. Ok.

**Comment by joannafarley-arm** [comment]
Closing PR as after squashing changes I could not get PR to automatically update.

**Pull request closed without merging**
