### PR TITLE
Add TF-RMM project to the website.

### PR DESCRIPTION
**Pull request by soby-mathew**
Signed-off-by: Soby Mathew <soby.mathew@arm.com>

### CODE REVIEW

**Comment by soby-mathew** [comment]
I haven't created the TF-RMM svg file but if someone can help provide that, that would be great.

**Comment by soby-mathew** [comment]
> I haven't created the TF-RMM svg file but if someone can help provide that, that would be great.

Thanks for providing the svg file. I have updated the PR.

**Comment by dbharbin** [comment]
For some reason the colors are inverted in you logo.   @kylekirkby  is the svg wrong or is this a setup issue?  
@soby-mathew  when are you wanting this to merge?  ASAP or is there a date in mind?

**Comment by soby-mathew** [comment]
@dharbin, some time next week is fine for merge.

**Comment by dbharbin** [comment]
Thanks so much for the 2 fixes @kylekirkby !    @soby-mathew   I can merge this whenever you're ready.  Just let me know.

**Comment by soby-mathew** [comment]
Thanks Kyle. Yes,  this can be merged.

**Pull request merged**
